version: "3.9"
services:
  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
